### PR TITLE
Replacing deprecated $BaseHref in template

### PR DESCRIPTION
**Pull request by 3Dgoo**
$BaseHref has been deprecated. I have replaced this in the template with $AbsoluteBaseURL.

### CODE REVIEW

**Comment by 3Dgoo** [comment]
Is there anything I can do to help these changes get merged in?

**Comment by frankmullenger** [comment]
@3Dgoo thanks for this, we currently have a composer dependency for ~3.1 on both cms and framework does that need to change? If so I guess we should merge this request into 2.1 branch along with composer change and tag a new release? Thoughts @stevie-mayhew @Zauberfisch @icecaster ?

**Comment by stevie-mayhew** [comment]
This shouldn't need to change the dependency we are relying on - it was actually deprecated at 3.0 but there is a `TemplateGlobalProvider` for Director which maps it to the new call. @frankmullenger this should just be merged as is IMHO.

**Comment by frankmullenger** [comment]
Awesome, thanks for checking that @stevie-mayhew. Cheers for the contribution @3Dgoo!

**Comment by stevie-mayhew** [comment]
:+1:

**Comment by 3Dgoo** [comment]
:+1: Nice work guys

**Pull request merged**
