### PR TITLE
BUG: options cannot be edited by anyone but the super admin

### PR DESCRIPTION
**Pull request by stevie-mayhew**
Allows non-admin users to manage options.

### CODE REVIEW

**Comment by frankmullenger** [comment]
@stevie-mayhew again, change looks great. Just a small request if possible for a stylistic change from spaces to hard tabs and opening brace on the same e.g: http://doc.silverstripe.org/framework/en/trunk/misc/coding-conventions#function-and-method-declaration

**Comment by stevie-mayhew** [comment]
Yep, don't worry about commenting the rest of them, I'll go through and switch out to SS standards rather than PSR for them in the morning.

**Comment by stevie-mayhew** [comment]
Actually, do you know of any IDEA profiles floating around which are set up for SS coding standards, would make life a lot easier when switching between work projects and SS stuff :smile:

**Comment by frankmullenger** [comment]
Not sure sorry, @edlinklater would probably be the man to ask about that..

**Comment by edlinklater** [comment]
I actually really like the PSR coding standards. Spaces for indentation can diaf though :wink: 

Don't know anything for IDEA that enforces SS coding standards, sorry.

**Comment by Zauberfisch** [comment]
as far as I know there is no fully finished profile for IDEA/phpstorm, however, there comes one with the silverstripe plugin that is quiet ok

**Comment by stevie-mayhew** [comment]
@frankmullenger I've changed the tab spacing and line endings on the rest of these pull requests. You may need to update the few which were already merged in, sorry about that!

**Pull request merged**
