### PR TITLE
Replace new Price() with Price::create() to allow it to be overridden with Object::hasCustomClass()

### PR DESCRIPTION
**Pull request by silverstripe-elliot**
This change will allow modules to extend the Price object, then allow it to be overridden with an extended class using Object::hasCustomClass()

### CODE REVIEW

**Comment by silverstripe-elliot** [comment]
The correct SHA is 79df5f3. I'm not sure why all these previous commits keep appearing in my branches after a fresh pull from the upstream. Any ideas?

**Comment by frankmullenger** [comment]
@silverstripe-elliot I'm not sure why that is...

**Comment by stevie-mayhew** [comment]
@frankmullenger @silverstripe-elliot I'll have a look at cherry picking out your commit and pulling it tomorrow morning at the hackfest for you (us) :smile:

**Comment by frankmullenger** [comment]
@stevie-mayhew you read my mind! https://github.com/swipestripe/silverstripe-swipestripe/pull/64 @silverstripe-elliot can you also double check this pull request is all good?

**Pull request closed without merging**
