### PR TITLE
Add the ability to override the title of the 'Quantity' field on the product form

### PR DESCRIPTION
**Pull request by erindru**
I had the need to have a custom title for the 'Quantity' field. It was hardcoded to 'Quantity' (which probably works in 99% of cases) but I needed to make it say something else.

Im not sure if this is the best approach since its very specific to the Quantity field and doesn't allow overriding and of the other field names. Could this approach be followed for other field names (eg, define a method for getting the title of each field name) or is there a better way?

### CODE REVIEW

**Comment by icecaster** [comment]
Hi Erin,

this can be done by getting the field instance, then calling setTitle on it.

Will dig out some code for you later

**Comment by erindru** [comment]
Is that done via the DataExtension or by some other means?

**Comment by icecaster** [comment]
DataExtension is for DataObjects, since you are working with a Form instance, use Extension instead.

Here is a code example:

```
<?php

class ProductForm_Extension extends Extension {
    function updateFields($fields) {
        $fields->renameField("Quantity", "Number of Cases");
    }
}

?>
```

then adding the extension via 

```
Object::add_extension("ProductForm", "ProductForm_Extension");
```

**Comment by erindru** [comment]
That works perfectly, thanks!

**Comment by icecaster** [comment]
Nice one!

You can do a lot of modifications through this interface, check FieldList::replaceByName() etc to replace the field altogether!

Cheers

**Comment by frankmullenger** [comment]
Awesome, thanks very much for handling this @icecaster. @erindru just ignore the email I sent you prior to reading this thread :-)

**Pull request closed without merging**
