### PR TITLE
UPDATE: allow variations to be enabled/disabled through extensions

### PR DESCRIPTION
**Pull request by stevie-mayhew**
:)

### CODE REVIEW

**Comment by frankmullenger** [comment]
Hey @stevie-mayhew, you have been busy! Your changes look great, I checked this one out and noticed a mixture of spaces and tabs, it's a really small thing but do you think you could convert to hard tabs?

**Comment by stevie-mayhew** [comment]
Ah yep, sorry I have my editor set to the PSR standards, not the SilverStripe ones. I'll go through all of these in the morning and convert my changes to tabs for you :)

**Comment by frankmullenger** [comment]
@stevie-mayhew Awesome, thanks mate. Appreciate all the pull requests, hackday at SilverStripe tomorrow and hopefully I will get these all merged in, feel free to drop by the office. Also, if you are interested in being added to the core dev team for SwipeStripe let me know!

**Comment by stevie-mayhew** [comment]
@frankmullenger cool, I might drop by around 10am to have a chat, if I can I'll ping Ed on IRC and let you know I'm coming. There are a few things which would be good to go over before I commit the time to making the transition from our internal base to here.

**Comment by frankmullenger** [comment]
Definitely, sounds good mate see you then.

**Comment by frankmullenger** [comment]
@stevie-mayhew some spaces might have made it through on this one still, can sort it out in a subsequent commit if you don't have the time to look into it though.

**Comment by stevie-mayhew** [comment]
@frankmullenger cool, thats done (I hope, fourth time lucky)

**Comment by frankmullenger** [comment]
Cheers mate!

**Pull request merged**
