### PR TITLE
set Product Qty field to type number

### PR DESCRIPTION
**Pull request by RuthAdele**
Good UX, especially for iPads etc., to bring up the correct keyboard.

### CODE REVIEW

**Comment by Zauberfisch** [comment]
I am not sure this is the right place to set the type of the field.

if its a numeric value, perhaps `ProductForm_QuantityField` sould simply subclass `NumericField` instead of `TextField`, not sure though if that also sets the html type attribute to number.
If using `NumericField` is not an option, or does not give us type number and we do go with `->setAttribute()`, I still think this is not the right place for it, it should be placed in the `ProductForm_QuantityField` constructor.

**Comment by RuthAdele** [comment]
Yeah, I tried subclassing NumericField first, surprisingly it doesn't set the type attribute :(
I'll have another look at it today at some point.

**Comment by Zauberfisch** [comment]
ok, could you perhaps open an issue on the SilverStripe framework regarding `NumericField` not using type number?

I think subclassing `NumericField`, and getting `NumericField` to use type number is the best of all possible options.

**Comment by RuthAdele** [comment]
I've opened an issue (https://github.com/silverstripe/silverstripe-framework/issues/3289), I suppose it's best to wait and cross fingers that it will be looked at, rather than trying to patch the field creation.

**Comment by Zauberfisch** [comment]
perfect.

if you subclass `NumericField` and create a pull request for it (or change this one), I am happy to merge it.

**Comment by RuthAdele** [comment]
Numeric field now has correct type in framework:
https://github.com/silverstripe/silverstripe-framework/pull/3361

**Comment by stevie-mayhew** [comment]
Nice work! Sorry to steal your thunder @Zauberfisch

**Pull request merged**
